local cursor = require "in.cursor"

local db = require "../utils/card_db"

go.property("minion", 0)

function init(self)
    local card_data = db[self.minion]
    msg.post("template", "content", {card_data = card_data})
end

function on_message(self, message_id, message)
    if message_id == cursor.OVER then
        msg.post("template", "over")
    elseif message_id == cursor.OUT then
        msg.post("template", "out")
    end
end
